#if !canImport(ObjectiveC)
import XCTest

extension StripeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StripeTests = [
        ("testDecodingCustomer_Metadata", testDecodingCustomer_Metadata),
        ("testDecodingCustomer", testDecodingCustomer),
        ("testDecodingDiscountJson", testDecodingDiscountJson),
        ("testDecodingPlan_WithNickname", testDecodingPlan_WithNickname),
        ("testDecodingPlan_WithoutNickname", testDecodingPlan_WithoutNickname),
        ("testDecodingSubscriptionWithDiscount", testDecodingSubscriptionWithDiscount),
        ("testRequests", testRequests),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StripeTests.__allTests__StripeTests),
    ]
}
#endif
