#if !canImport(ObjectiveC)
import XCTest

extension StyleguideTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StyleguideTests = [
        ("testGitHubLink_Black", testGitHubLink_Black),
        ("testGitHubLink_White", testGitHubLink_White),
        ("testPointFreeStyles", testPointFreeStyles),
        ("testStyleguide", testStyleguide),
        ("testTwitterLink", testTwitterLink),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StyleguideTests.__allTests__StyleguideTests),
    ]
}
#endif
