FROM swift:5.10-focal

RUN apt-get --fix-missing update
RUN apt-get install -y cmake libpq-dev libz-dev python

WORKDIR /build

COPY .pf-env* ./
COPY Makefile .
COPY Package.resolved .
COPY Package.swift .
COPY Sources ./Sources
COPY Tests ./Tests

RUN swift build --build-tests --jobs 1

CMD .build/debug/Server
