extension Episode.Collection {
  public static let all: [Self] = [
    .modernPersistence,
    .swiftUI,
    .backToBasics,
    .composableArchitecture,
    .sqlite,
    .concurrency,
    .uiKit,
    .crossPlatform,
    .macros,
    .dependencies,
    .livestreams,
    .parsing,
    .caseStudies,
    .wwdc,
    .tours,
    .combine,
    .protocolWitnesses,
    .mapZipFlatMap,
    .algebraicDataTypes,
    .enumsAndStructs,
    .domainSpecificLanguages,
    .randomness,
  ]
}
