#if !canImport(ObjectiveC)
import XCTest

extension FunctionalCssTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionalCssTests = [
        ("testFunctionalCss", testFunctionalCss),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FunctionalCssTests.__allTests__FunctionalCssTests),
    ]
}
#endif
