#if !canImport(ObjectiveC)
import XCTest

extension PointFreeRouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PointFreeRouterTests = [
        ("testSubscribeRoute", testSubscribeRoute),
        ("testUpdateProfile", testUpdateProfile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PointFreeRouterTests.__allTests__PointFreeRouterTests),
    ]
}
#endif
