#if !canImport(ObjectiveC)
import XCTest

extension GitHubTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitHubTests = [
        ("testRequests", testRequests),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GitHubTests.__allTests__GitHubTests),
    ]
}
#endif
