import Css
import Prelude

public let spacing: Stylesheet =
  padding0 % padding(all: 0)
    <> padding0_5 % padding(all: .rem(0.5))
    <> padding1 % padding(all: .rem(1))
    <> padding2 % padding(all: .rem(2))
    <> padding3 % padding(all: .rem(3))
    <> padding4 % padding(all: .rem(4))
    <> padding5 % padding(all: .rem(5))

    <> paddingTop0 % padding(top: 0)
    <> paddingTop0_5 % padding(top: .rem(0.5))
    <> paddingTop1 % padding(top: .rem(1))
    <> paddingTop2 % padding(top: .rem(2))
    <> paddingTop3 % padding(top: .rem(3))
    <> paddingTop4 % padding(top: .rem(4))
    <> paddingTop5 % padding(top: .rem(5))

    <> paddingBottom0 % padding(bottom: 0)
    <> paddingBottom0_5 % padding(bottom: .rem(0.5))
    <> paddingBottom1 % padding(bottom: .rem(1))
    <> paddingBottom2 % padding(bottom: .rem(2))
    <> paddingBottom3 % padding(bottom: .rem(3))
    <> paddingBottom4 % padding(bottom: .rem(4))
    <> paddingBottom5 % padding(bottom: .rem(5))

    <> paddingLeft0 % padding(left: 0)
    <> paddingLeft0_5 % padding(left: .rem(0.5))
    <> paddingLeft1 % padding(left: .rem(1))
    <> paddingLeft2 % padding(left: .rem(2))
    <> paddingLeft3 % padding(left: .rem(3))
    <> paddingLeft4 % padding(left: .rem(4))
    <> paddingLeft5 % padding(left: .rem(5))

public let padding0 = CssSelector.class("p0")
public let padding0_5 = CssSelector.class("p0_5")
public let padding1 = CssSelector.class("p1")
public let padding2 = CssSelector.class("p2")
public let padding3 = CssSelector.class("p3")
public let padding4 = CssSelector.class("p4")
public let padding5 = CssSelector.class("p5")

public let paddingTop0 = CssSelector.class("pt0")
public let paddingTop0_5 = CssSelector.class("pt0_5")
public let paddingTop1 = CssSelector.class("pt1")
public let paddingTop2 = CssSelector.class("pt2")
public let paddingTop3 = CssSelector.class("pt3")
public let paddingTop4 = CssSelector.class("pt4")
public let paddingTop5 = CssSelector.class("pt5")

public let paddingBottom0 = CssSelector.class("pb0")
public let paddingBottom0_5 = CssSelector.class("pb0_5")
public let paddingBottom1 = CssSelector.class("pb1")
public let paddingBottom2 = CssSelector.class("pb2")
public let paddingBottom3 = CssSelector.class("pb3")
public let paddingBottom4 = CssSelector.class("pb4")
public let paddingBottom5 = CssSelector.class("pb5")

public let paddingLeft0 = CssSelector.class("pl0")
public let paddingLeft0_5 = CssSelector.class("pl0_5")
public let paddingLeft1 = CssSelector.class("pl1")
public let paddingLeft2 = CssSelector.class("pl2")
public let paddingLeft3 = CssSelector.class("pl3")
public let paddingLeft4 = CssSelector.class("pl4")
public let paddingLeft5 = CssSelector.class("pl5")
