#if !canImport(ObjectiveC)
import XCTest

extension DatabaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DatabaseTests = [
        ("testCreateSubscription_OwnerIsNotTakingSeat", testCreateSubscription_OwnerIsNotTakingSeat),
        ("testCreateSubscription_OwnerIsTakingSeat", testCreateSubscription_OwnerIsTakingSeat),
        ("testFetchEnterpriseAccount", testFetchEnterpriseAccount),
        ("testUpsertUser_FetchUserById", testUpsertUser_FetchUserById),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DatabaseTests.__allTests__DatabaseTests),
    ]
}
#endif
